export enum SearchPanelLocators {
  BTN_DESTINATION_INPUT = '[data-selenium="textInput"]',
  AUTOSUGGEST_ITEM = '[data-selenium="autosuggest-item"]',
  BTN_CHECKIN_DATE = '[data-selenium="checkInBox"]',
  BTN_ADD_ROOM = '[aria-label="Add Room"]',
  BTN_ADD_ADULTS = '[data-element-name="occupancy-selector-panel-adult"][data-selenium="plus"]',
  BTN_ADD_CHILDREN = '[aria-label="Add Children"]',
  BTN_SEARCH = 'button[data-element-name="search-button"]',
  BTN_DAY_USE_STAYS = 'button[label="Day Use Stays"]',
  LBL_DAY_USE_DESCRIPTION = '[data-name="searchbox-funnel-description"]',
  BTN_OCCUPANCY = '[data-element-name="occupancy-box"]',
  BTN_TAB_HOMES_AND_APTS = '[id="tab-home"]',
  BTN_TAB_HOTELS = '[id="tab-all-rooms-tab"]',
  BTN_TAB_FLIGHT_HOTEL = '[id="tab-packages-tab"]',
  BTN_TAB_FLIGHTS = '[id="tab-flight-tab"]',
  BTN_TAB_ACTIVITIES = '[id="tab-activities-tab"]',
  BTN_TAB_AIRPORT_TRANSFER = '[id="tab-journey-tab"]',
}
